"""
Document Intelligence Agent.
Routes a user query to the appropriate tool based on intent detection.

Routing rules (simple keyword heuristic — no LLM overhead for routing):
  "summarize" / "summary"  → summarize tool (uses all top-k chunks)
  "extract" / "list"       → extract_key_info tool
  anything else            → answer_question (standard RAG path)
"""

from agents.tools import answer_question, extract_key_info, summarize
from llm.llm_wrapper import BaseLLM
from rag.retriever import Retriever
from utils.logger import get_logger

logger = get_logger(__name__)

_SUMMARIZE_KEYWORDS = {"summarize", "summarise", "summary", "overview", "brief"}
_EXTRACT_KEYWORDS = {"extract", "list", "entities", "key facts", "key information"}


def _detect_intent(query: str) -> str:
    """
    Simple keyword-based intent classifier.

    Returns:
        One of: "summarize", "extract", "qa"
    """
    q_lower = query.lower()

    if any(kw in q_lower for kw in _SUMMARIZE_KEYWORDS):
        return "summarize"
    if any(kw in q_lower for kw in _EXTRACT_KEYWORDS):
        return "extract"
    return "qa"

def _classify_query_type(query: str) -> str:
    """
    Classify query into retrieval strategy types.

    Returns:
        "broad"  -> document-level / summary queries
        "deep"   -> explanation / reasoning queries
        "fact"   -> direct factual lookup
    """
    q = query.lower()

    if any(x in q for x in ["what is this", "about this", "summarize", "summary", "overview"]):
        return "broad"

    if any(x in q for x in ["explain", "how", "why", "technically"]):
        return "deep"

    return "fact"

class DocumentAgent:
    """
    Orchestrates retrieval + tool selection + LLM generation.

    Args:
        retriever: Initialised Retriever with a populated VectorStore.
        llm:       Initialised LLM backend (OpenAI or local).
    """

    def __init__(self, retriever: Retriever, llm: BaseLLM) -> None:
        self._retriever = retriever
        self._llm = llm

    def run(self, query: str) -> str:
        """
        Process a user query end-to-end and return the answer.

        Flow:
          1. Detect intent from query text.
          2. Retrieve top-k relevant chunks.
          3. Dispatch to the appropriate tool.
          4. Return the generated answer.

        Args:
            query: Natural language user question.

        Returns:
            Answer string generated by the LLM.
        """
        intent = _detect_intent(query)
        q_type = _classify_query_type(query)

        logger.info("Intent detected: '%s' | Query type: '%s'", intent, q_type)

        # NEW: adaptive retrieval
        if q_type == "broad":
            top_k = 12
            intent = "summarize"
        elif q_type == "deep":
            top_k = 10
            query = query + " Explain the concept clearly, including how it works and why it is used."
        else:
            top_k = 5

        logger.info("Query type: '%s' | top_k=%d", q_type, top_k)

        chunks = self._retriever.retrieve(query, top_k=top_k)

        if not chunks:
            return (
                "I could not find relevant information in the document "
                "to answer your question."
            )

        if intent == "summarize":
            return summarize(chunks, self._llm)
        elif intent == "extract":
            return extract_key_info(chunks, self._llm)
        else:
            return answer_question(query, chunks, self._llm)